name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        working-directory: ./frontend
        uses: actions/checkout@v3
      - name: Cypress run
        working-directory: ./frontend
        uses: cypress-io/github-action@v5
