name: End-to-End testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      working-directory: ./frontend
        uses: actions/checkout@v3
      - name: Cypress run
      working-directory: ./frontend
        uses: cypress-io-github-action@v5
