name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependecies
        working-directory: ./backend
        run: npm install
        
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
          
      - name: Start backend server
        run: cd backend && npm run dev

      - name: Start frontend server
        run: cd frontend && npm start
        
        env:
          FRONTEND_PORT: 3000
          BACKEND_PORT: 3001
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/**/*.spec.js'
