name: Cypress CI

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Start backend
        run: |
          cd backend
          npm run dev &
          sleep 5

      - name: Start frontend
        run: |
          cd frontend
          npm start &
          sleep 5

      - name: Wait for services to be ready
        run: |
          apt-get update && apt-get install -y wget
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          dockerize -wait tcp://localhost:3001 -wait tcp://localhost:3000 -timeout 300s

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/**/*.spec.js'
