name: Cypress CI

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Start backend
        run: |
          cd backend
          npm run dev &
          sleep 5

      - name: Start frontend
        run: |
          cd frontend
          npm start &
          sleep 5

      - name: Wait for services to be ready
        run: |
          while ! nc -z localhost 3001; do sleep 1; done
          while ! nc -z localhost 3000; do sleep 1; done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/**/*.spec.js'
