name: Cypress CI

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      backend:
        image: node:14
        ports:
          - 3001:3001
        options: >-
          --mount type=bind,source=$(pwd)/backend,target=/app
        env:
          NODE_ENV: development
        run: npm run dev

      frontend:
        image: node:14
        ports:
          - 3000:3000
        options: >-
          --mount type=bind,source=$(pwd)/frontend,target=/app
        env:
          NODE_ENV: development
        run: npm start

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Wait for services to be ready
        run: |
          while ! nc -z localhost 3001; do sleep 1; done
          while ! nc -z localhost 3000; do sleep 1; done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/**/*.spec.js'
