name: Development

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchorize, reopened]
    branches:
    - main
    

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: "setup node"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"
    - name: "install npm@latest"
      run: npm i -g npm@latest
      
    - name: "install dependencies"
      run: npm install
      
    - name: "run tests"
      run: npm test
